# Generated by Django 2.0.2 on 2018-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='aa', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
    ]
